### ISSUE TITLE
ML Roadmap

### ISSUE THREAD

**Issue by AmirAziz1221** [AmirAziz1221/Data-Analysis-using-jupyter-Notebook#3]
Please some one share me a complete road map for machine learning @AmirAziz1221

**Comment by AmirAziz1221** [comment]
Guide me plz

**Comment by Azizdawar** [comment]
Check it @AmirAziz1221  
![download](https://github.com/AmirAziz1221/Data-Analysis-using-jupyter-Notebook/assets/129350170/f1fd6ab2-9ee9-4d18-8872-b70427dbf1e6)

**Comment by AmirAziz1221** [comment]
Thanks

**Comment by AmirAziz1221** [comment]
awosome work
